import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins, Orbitron, Rajdhani } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Layout/Navbar";
import Footer from "@/components/Layout/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const orbitron = Rajdhani({
  subsets: ['latin'],
  weight: ['400', '700'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Dip",
  description: "Generated by create next app",
  // icons: {
  //   icon: "/DBPLogo.png",
  // },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={orbitron.className}
      >
        <Navbar/>
            <div id="page-body">{children}</div>
        <Footer /> 
      </body>
    </html>
  );
}
